### ISSUE TITLE
make it responsive

### ISSUE THREAD

**Issue by Pranay0302** [42ip/0x5A#2]
current prototype has some issues with responsiveness and there are lots of bugs related to UX and responsiveness of the app.

**Comment by Godwindaniel10** [comment]
Hi, I am Godwin, I will love to contribute to this issue

**Comment by Pranay0302** [comment]
@Godwindaniel10 Sure, Go Ahead!

**Comment by Godwindaniel10** [comment]
ok

**Comment by Godwindaniel10** [comment]
ran into an issue,  local host not loading on my machine      http://localhost:3000]

**Comment by Godwindaniel10** [comment]
http://localhost:3000

**Comment by Pranay0302** [comment]
1. Make sure you install all the packages `npm i `
2. Later `npm start`

**Comment by Godwindaniel10** [comment]
ok now it works

**Comment by Godwindaniel10** [comment]
hi, I made the navbar responsive, I want to do that to the form field as well, but I cant find the code. i am not a react dev tho😃

**Comment by Pranay0302** [comment]
Alright np, Send a pr and I'll review the code.

**Comment by Godwindaniel10** [comment]
ok

**Comment by Pranay0302** [comment]
#3 clears this issue.
