### ISSUE TITLE
adding better styling

### ISSUE THREAD

**Issue by Pranay0302** [42ip/0x5A#5]
color palette - https://colorhunt.co/palette/171392

based on this color palette, style it up.

**Comment by DineshKoushik** [comment]
@Pranay0302  I'll give it a try

**Comment by Pranay0302** [comment]
Sure, Go ahead.

**Comment by DineshKoushik** [comment]
Hi @Pranay0302 can you review the pull request.

**Comment by Pranay0302** [comment]
@DineshKoushik Thank you for contributing
